title: Russell.M.Harmon
email: russellmharmon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Game audio designer
baseurl: ""
url: "http://russellmharmon.com"
twitter_username: russellmharmon
github_username:  russellmharmon

markdown: kramdown
sass:
  style: compressed
