title: Russell Harmon
email: russellmharmon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sound Designer
baseurl: ""
url: "http://russellmharmon.com"
github_username:  russellmharmon

markdown: kramdown
sass:
  style: compressed
